### ISSUE TITLE
How to install and run this code

### ISSUE THREAD

**Issue by jing1234** [jasonwebb/SurfaceMapperGUI#2]
Hi,
Maybe is there tutor to show, how to use this code? I can't run the code, there are many problem.

If somebody share me a tutor for this, that will be great.

Thanks so much,
Jing

**Comment by jasonwebb** [comment]
The best I can offer you is an old tutorial I wrote when I first released this tool years ago: http://jason-webb.info/2013/11/surfacemappergui-a-simple-processing-interface-for-projection-mapping/

Since this is a somewhat experimental, open-source, and admittedly amateur-ish application, its expected that you know a fair amount about Processing on your own, such as installing a specific version, installing libraries, and getting projects from source control up and running in your personal environment.

Really the best resource I can point you to is the source code itself. If you have experience with Processing I think you'd be able to understand what this sketch is doing, and how, and be able to trace down and correct any problems that may occur.
